"""Add ScanImage and scan_mode

Revision ID: 963ee36b1eaf
Revises: 
Create Date: 2026-09-19 16:33:03.036621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963ee36b1eaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_mode', sa.String(length=20), server_default='deep', nullable=False))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'official'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'official'::character varying"))
        batch_op.drop_column('scan_mode')

    # ### end Alembic commands ###
